CREATE TABLE cell_line(
       cell_line_id int unsigned NOT NULL AUTO_INCREMENT,
       name char(18) NOT NULL,
       short_name char(7) NOT NULL,
       biosample_id char(12),
       cell_type varchar(255),
       is_on_feeder tinyint,
       gender varchar(255),
       age varchar(255),
       disease varchar(255),
       ethnicity varchar(255),
       derived_from_tissue_type varchar(255),
       reprogramming varchar(255),
       PRIMARY KEY (cell_line_id),
       UNIQUE INDEX (name),
       UNIQUE INDEX (short_name)
) ENGINE=InnoDB;

CREATE TABLE experiment(
       experiment_id int unsigned NOT NULL AUTO_INCREMENT,
       cell_line_id int unsigned NOT NULL,
       evaluation_guid char(36) NOT NULL,
       p_col tinyint unsigned NOT NULL,
       p_row tinyint unsigned NOT NULL,
       num_nuclei unsigned smallint NOT NULL,
       num_cells unsigned smallint NOT NULL,
       cell_nuc_area_mean float,
       cell_nuc_area_sd float,
       cell_nuc_area_sum float,
       cell_nuc_area_max float,
       cell_nuc_area_min float,
       cell_nuc_area_median float,
       edu_median_mean float,
       edu_median_sd float,
       edu_median_sum int,
       edu_median_max mediumint,
       edu_median_min mediumint,
       edu_median_median mediumint,
       oct_median_mean float,
       oct_median_sd float,
       oct_median_sum int,
       oct_median_max mediumint,
       oct_median_min mediumint,
       oct_median_median mediumint,
       inten_nuc_dapi_median_mean float,
       inten_nuc_dapi_median_sd float,
       inten_nuc_dapi_median_sum int,
       inten_nuc_dapi_median_max mediumint,
       inten_nuc_dapi_median_min mediumint,
       inten_nuc_dapi_median_median mediumint,
       cells_per_clump_mean float,
       cells_per_clump_sd float,
       cells_per_clump_sum smallint,
       cells_per_clump_max smallint,
       cells_per_clump_min smallint,
       cells_per_clump_median smallint,
       area_mean float,
       area_sd float,
       area_sum float,
       area_max float,
       area_min float,
       area_median float,
       roundness_mean float,
       roundness_sd float,
       roundness_sum float,
       roundness_max float,
       roundness_min float,
       roundness_median float,
       ratio_w2l_mean float,
       ratio_w2l_sd float,
       ratio_w2l_sum float,
       ratio_w2l_max float,
       ratio_w2l_min float,
       ratio_w2l_median float,
       num_singles smallint,
       compound varchar(255),
       concentration float,
       cell_type varchar(255),
       cell_count smallint,
       num_fields tinyint NOT NULL,
       PRIMARY KEY (experiment_id),
       UNIQUE INDEX (p_col, p_row, evaluation_guid),
       FOREIGN KEY fk_experiment_line_line_id (cell_line_id) REFERENCES cell_line(cell_line_id)
) ENGINE=InnoDB;

CREATE TABLE cell(
       cell_id int unsigned NOT NULL AUTO_INCREMENT,
       experiment_id int unsigned NOT NULL,
       field tinyint unsigned NOT NULL,
       i_cell smallint NOT NULL,
       i_clump smallint NOT NULL,
       i_nuc smallint NOT NULL,
       i_nuc2 smallint NOT NULL,
       x_centroid smallint unsigned NOT NULL,
       x_left smallint unsigned NOT NULL,
       x_right smallint unsigned NOT NULL,
       y_centroid smallint unsigned NOT NULL,
       y_bottom smallint unsigned NOT NULL,
       y_top smallint unsigned NOT NULL,
       cell_area float unsigned NOT NULL,
       nucleus_area float unsigned NOT NULL,
       edu_median mediumint unsigned NOT NULL,
       oct_median mediumint unsigned NOT NULL,
       inten_nuc_dapi_median mediumint unsigned NOT NULL,
       roundness float NOT NULL,
       ratio_w2l float NOT NULL,
       clump_size smallint NOT NULL,
       PRIMARY KEY (cell_id),
       FOREIGN KEY fk_cell_experiment_experiment_id (experiment_id) REFERENCES experiment(experiment_id)
) ENGINE=InnoDB;
